### ISSUE TITLE
Publish 2.5.0 to Chef Supermarket

### ISSUE THREAD

**Issue by jeffbyrnes** [SimpleFinance/chef-zookeeper#111]
@jakedavis looks like v2.5.0 never made it to the Supermarket. Would be lovely to have it in there, seeing as it’s already been bumped & tagged here.

**Comment by jeffbyrnes** [comment]
Published v2.5.0 to Supermarket.

**Comment by jakedavis** [comment]
Hey @jeffbyrnes, wanted to apologize again for being terrible at this. Really appreciate you taking the time here.
