### ISSUE TITLE
zookeeper::install is not idempotent

### ISSUE THREAD

**Issue by stensonb** [SimpleFinance/chef-zookeeper#119]
it untars and chown's the folder on each chef-client run:

somebox01 Recipe: zookeeper::install
somebox01   * zookeeper[3.4.6] action install
somebox01   Recipe: <Dynamically Defined Resource>
somebox01     * chef_gem[zookeeper] action install (up to date)
somebox01     * chef_gem[json] action install (up to date)
somebox01     * group[zookeeper] action create (up to date)
somebox01     * user[zookeeper] action create (up to date)
somebox01     * remote_file[zookeeper-3.4.6] action create (up to date)
somebox01     * directory[/opt/zookeeper] action create (up to date)
somebox01     * execute[install zookeeper] action run
somebox01       - execute tar -C /opt/zookeeper -zxf zookeeper-3.4.6.tar.gz
somebox01       chown -R zookeeper:zookeeper /opt/zookeeper

**Comment by jakedavis** [comment]
Oh dang, we missed this one eh? Should be a relatively easy fix, I think.

**Comment by stensonb** [comment]
I agree...it doesn't bother me enough to fix it (yet!), but it should be relatively easy...I just wanted to get it documented here. :)

**Comment by stensonb** [comment]
To be fair, I was using version 2.4.1 of the cookbook...just upgraded to 2.5.0 via Berks...

...and, it looks like this is fixed in 2.5.0.

when is the newest release going to be pushed to the community site?
