### ISSUE TITLE
Missing supported versions

### ISSUE THREAD

**Issue by spuder** [SimpleFinance/chef-zookeeper#120]
It would be nice if this listed the supported operating systems on the chef super market. 

Does it work with Ubuntu?
Does it work with CentOs?

**Comment by jeffbyrnes** [comment]
@spuder until we get the metadata updated & a new version released, I can tell you this cookbook definitely works with Ubuntu 14.04, and likely also 12.04. Can’t speak for CentOS or RHEL-based systems, however.
