### ISSUE TITLE
Update zookeeper version to 3.4.6

### ISSUE THREAD

**Issue by paweloczadly** [SimpleFinance/chef-zookeeper#123]
```
$ chef-solo ...
....
  * remote_file[/var/chef/cache/zookeeper-3.4.5.tar.gz] action create
    - create new file /var/chef/cache/zookeeper-3.4.5.tar.gz[2015-01-21T08:04:18+00:00] WARN: remote_file[/var/chef/cache/zookeeper-3.4.5.tar.gz] cannot be downloaded from http://mirrors.ibiblio.org/apache/zookeeper/zookeeper-3.4.5/zookeeper-3.4.5.tar.gz: 404 "Not Found"

    ================================================================================
    Error executing action `create` on resource 'remote_file[/var/chef/cache/zookeeper-3.4.5.tar.gz]'
    ================================================================================
    
    Net::HTTPServerException
    ------------------------
    404 "Not Found"
```

**Comment by paweloczadly** [comment]
ah sorry... I see that it is updated. However, Berkshelf downloads older version of your cookbook with zookeeper 3.4.5

**Comment by jeffbyrnes** [comment]
@paweloczadly hmm, that's odd. Berkshelf should be grabbing v2.5.1 from Supermarket, which has its attributes set to install Zookeeper v3.4.6.

Please double-check your attributes in your wrapper cookbook, and also that you've not set your metadata or Berksfile to download a version less than v2.0.0. As long as you’ve set `depends 'zookeeper', '~> 2.0'`, you’ll install zookeeper 3.4.6.

**Comment by jeffbyrnes** [comment]
No response for over a month, closing out.
