### ISSUE TITLE
Classpath has version 3.4.6 hard-coded

### ISSUE THREAD

**Issue by patoarvizu** [SimpleFinance/chef-zookeeper#134]
[This line](https://github.com/SimpleFinance/chef-zookeeper/blob/master/templates/default/environment-defaults.erb#L5) has version 3.4.6 hardcoded, it prevents any version other than 3.4.6 to work.

**Comment by jeffbyrnes** [comment]
That’s… pretty important to fix. Thanks!

**Comment by spuder** [comment]
This is a big bug now that 3.4.6 doesn't appear to be available on any of the mirrors. 

http://apache.mirrorcatalogs.com/zookeeper/zookeeper-3.4.7/

http://www.poolsaboveground.com/apache/zookeeper/

**Comment by jeffbyrnes** [comment]
@spuder understood. I’ll get it sorted; it’s blocking us, too, now.

**Comment by jeffbyrnes** [comment]
@spuder @patoarvizu alrighty, I’ve published [v3.0.0](https://supermarket.chef.io/cookbooks/zookeeper/versions/3.0.0) to Supermarket to solve this.
