### ISSUE TITLE
Wrapper cookbooks are hard coded to use version 3.4.6 because not using lazy evaluation

### ISSUE THREAD

**Issue by spuder** [SimpleFinance/chef-zookeeper#151]
This is related to https://github.com/SimpleFinance/chef-zookeeper/issues/134

Because the default.rb file sets an attribute based on another attribute, this causes wrapper cookbooks to fail to overwrite the installation path. 

Base cookbook
```ruby
default[:zookeeper][:version]     = '3.4.6'
default[:zookeeper][:config_dir]  = "#{node[:zookeeper][:install_dir]}/" \
                                    "zookeeper-#{node[:zookeeper][:version]}/conf"
```

```ruby
If you then do the following in your wrapper cookbook
default[:zookeeper][:version] = '3.4.7'
```

```ruby
zookeeper_config "#{node[:zookeeper][:config_dir]}//#{node[:zookeeper][:conf_file]}" do
  config node[:zookeeper][:config]
  user   node[:zookeeper][:user]
  action :render
end
```

You will get the following error

```ruby
Recipe: nd-zookeeper::default
         * zookeeper_config[/opt/zookeeper/zookeeper-3.4.6/conf//zoo.cfg] action render
         Recipe: <Dynamically Defined Resource>
           * file[/opt/zookeeper/zookeeper-3.4.6/conf//zoo.cfg] action create
             * Parent directory /opt/zookeeper/zookeeper-3.4.6/conf does not exist.
             ================================================================================
             Error executing action `create` on resource 'file[/opt/zookeeper/zookeeper-3.4.6/conf//zoo.cfg]'
             ================================================================================

             Chef::Exceptions::EnclosingDirectoryDoesNotExist
             ------------------------------------------------
             Parent directory /opt/zookeeper/zookeeper-3.4.6/conf does not exist.

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cookbooks/zookeeper/providers/config.rb:19:in `block in class_from_file'

             Compiled Resource:
             ------------------
             # Declared in
```

Took me a while to understand what was happening since 3.4.6 is not hard coded anywhere in my wrapper cookbook. This blog post explains it clearly. 

https://coderanger.net/derived-attributes/

**Comment by spuder** [comment]
The work around is to make sure to set the following on the wrapper cookbook in the default attributes

    default[:zookeeper][:config_dir]  = "#{node[:zookeeper][:install_dir]}/zookeeper-#{node[:zookeeper][:version]}/conf"

**Comment by jeffbyrnes** [comment]
Hmm; it’s unclear to me if the derived attributes solution @coderanger proposes can just be used like so:

```ruby
default[:zookeeper][:version]     = '3.4.6'
default[:zookeeper][:config_dir]  = "%{node[:zookeeper][:install_dir]}/" \
                                    "zookeeper-%{node[:zookeeper][:version]}/conf"
```

or if more is needed (which his code suggests).

**Comment by spuder** [comment]
I've been experimenting with this for a couple hours in my fork. No luck yet. I still can't quite wrap my brain around what the correct solution is. 

https://github.com/spuder/chef-zookeeper/commit/7380a96aed13ab08e757fe65ae2e9d36d72f391a

**Comment by jeffbyrnes** [comment]
In the past, I’ve dealt with this by moving the derived attribute to a recipe, but that won’t necessarily work here, since this cookbook is primarily a library cookbook, and an end-user may not utilize the recipe(s).

**Comment by spuder** [comment]
For reference keeping track of everything I've tried https://gist.github.com/spuder/c96d5e9f2b0eebe2bd0c

This will be harder to troubleshoot on the 3.x branch. 

From conversations on IRC it sounds like it needs to be something like this: 

```ruby
config_dir = #{node[:zookeeper][:config_dir]} % { :config_dir => node[:zookeeper][:config_dir] }
config_file = #{node[:zookeeper][:config_file]} % { :config_file => node[:zookeeper][:config_file] }
zookeeper_config "whatever" do
  path "#{config_dir}/#{config_file}
  config node[:zookeeper][:config]
  user   node[:zookeeper][:user]
  action :render
end
```

**Comment by spuder** [comment]
I've returned to working on this, however since the derived attribute is based off of a derived attribute, I still get an error that I haven't been able to work around. Not even overriding the config_dir attribute locally works. 

Reaching out to SO for assistance. http://stackoverflow.com/questions/34163640/can-chef-lazy-load-multiple-attributes
