### ISSUE TITLE
adding --server configs to zoo.cfg

### ISSUE THREAD

**Issue by aktarali** [SimpleFinance/chef-zookeeper#155]
Hi;

I have found a problem with this cookbook or the implementation on my side. I have multiple slaves that try to join the cluster, however, they have been given the zk parameter for all masters, the problem is some nodes find the LIVE master and are able to register themselves getting a unique ID others attempt to register with the non Live master and they are not being re-directed to the primary master node and are not able to register.

I tried different settings and ended up adding the --server.1, .2 and 3 to the zoo.cfg file manually. Is there something that can be done with this cookbook to get the backup masters to tell the slaves about the LIVE master so that they can join correctly? I am running a mesos cluster solution.

Your help in this regard will be greatly appreciated.

Thanks
ALi.

**Comment by jeffbyrnes** [comment]
@aktarali I’m not entirely sure how you mean by “live” versus “non-live” master. We use the [`exhibitor`](https://github.com/SimpleFinance/chef-exhibitor) cookbook to handle configuration of the cluster, which makes things much easier (esp. since it can read a shared config file from S3).

However, if you were to just use this cookbook, you would need to add an entry for each of the servers to the `node[:zookeeper][:config]` attribute, as well as some other values (pulling this from the [ZK docs on setting up a quorum](http://zookeeper.apache.org/doc/r3.4.7/zookeeperStarted.html#sc_RunningReplicatedZooKeeper)):

```ruby
# your wrapper cookbook’s attributes/default.rb or similar:

set['zookeeper']['config']['tickTime'] = 2000
set['zookeeper']['config']['initLimit'] = 11
set['zookeeper']['config']['syncLimit'] = 17
set['zookeeper']['config']['server.1'] = 'zoo1:2888:3888'
set['zookeeper']['config']['server.2'] = 'zoo2:2888:3888'
set['zookeeper']['config']['server.3'] = 'zoo3:2888:3888'
```

Important to note: while this cookbook does use symbols for its attribute keys, the period is an illegal character for a ruby symbol, so I’ve used strings for the keys instead. I.e., `node['zookeeper'] == node[:zookeeper]`.

You could probably find your ZK nodes via Chef search & set the attributes that way:

```ruby
i = 0
search(:node,
       "chef_environment:#{node.chef_environment} AND " \
       'roles:zookeeper').map do |n|
  i += 1
  node.set['zookeeper']['config']["server.#{i}"] =
    "#{n['fqdn']}:2888:3888"
end
```

I can’t promise that search will work, and you might end up shuffling the servers around if the search changes the order, but that should give you something to work off of.

Or just use Exhibitor :wink:

**Comment by fnicholas** [comment]
Do you mind clarifying how to use Exhibitor with respect to this cookbook?

**Comment by williamsjj** [comment]
@jeffbyrnes 

chef-exhibitor depends on chef-zookeeper, so chef-zookeeper needs to be on your chef server, but chef-exhibitor will handle the install of zookeeper for you.

Here is a wrapper cookbook that works for us: https://gist.github.com/williamsjj/9839b99a5ed0f3f6103f

**Comment by jeffbyrnes** [comment]
@fnicholas yes, that’s the cookbook to use. You would wrap that cookbook in the manner that @williamsjj indicates. As it tightly depends on the `zookeeper` cookbook, it will handling including the necessary recipes from this cookbook, installing & configuring ZK, then install & configure Exhibitor, which will start itself up, and then manage the ZK processes for you.

I’m going to go ahead & close this issue, as we’ve gotten off-topic here.

**Comment by williamsjj** [comment]
@jeffbyrnes It might be helpful to have a short comment and example of wrapping the cookbook properly in the README. It took me about an hour of spelunking through both cookbooks to get it right.

**Comment by jeffbyrnes** [comment]
@williamsjj yeah, I’ve opened an issue on the `exhibitor` cookbook to cover doing just that. Thanks for sticking with it & sorting it out.

**Comment by fnicholas** [comment]
@williamsjj - thank you for your assistance. if I want to configure a 3 node zookeeper cluster using chef-exhibitor (which depends on chef-zookeeper) how should I do about it? Im trying to figure out where to put the nodes and how to write the wrapper cookbook recipe. Any information you provide will be very helpful.

**Comment by fnicholas** [comment]
here's my attributes/default.rb
```bash
default[:zookeeper][:version]     = '3.4.6'
default[:zookeeper][:checksum]    = '01b3938547cd620dc4c93efe07c0360411f4a66962a70500b163b59014046994'
default[:zookeeper][:mirror]      = 'http://www.poolsaboveground.com/apache/zookeeper'
default[:zookeeper][:user]        = 'zookeeper'
default[:zookeeper][:install_dir] = '/opt/zookeeper'
default[:zookeeper][:java_opts] = "-Xms128M -Xmx512M"
default[:zookeeper][:service_style] = 'exhibitor'
node.set['exhibitor']['cli']['port'] = 8700
node.set['zookeeper']['config']['tickTime'] = 2000
node.set['zookeeper']['config']['initLimit'] = 11
node.set['zookeeper']['config']['syncLimit'] = 17
node.set['zookeeper']['config']['server.1'] = '10.187.64.49:2888:3888'
node.set['zookeeper']['config']['server.2'] = '10.187.64.50:2888:3888'
node.set['zookeeper']['config']['server.3'] = '10.184.25.239:2888:3888'
```

and my recipes/default.rb
```bash
node.set['exhibitor']['cli']['port'] = 8700
include_recipe "exhibitor::default"
include_recipe "exhibitor::service"
```

I'm I missing anything else? Please help me out here.

**Comment by williamsjj** [comment]
@jeffbyrnes Sorry about the reference to you in my initial comment...I meant to reference fnicholas as opposed to looking like a shout out to you. :)

@fnicholas In your wrapper you're going to want attributes at a higher level than default to ensure they deterministically override the cookbooks you're wrapping. Also, I'd consider handling your overrides using node.set syntax in recipes/default.rb as I've found them more reliable, but that's a personal preference. You should spend some time digging into wrapper cookbooks in general to learn what works for you: 

* http://stackoverflow.com/questions/28466623/chef-wrapper-cookbook-best-practices
* https://www.chef.io/blog/2013/12/03/doing-wrapper-cookbooks-right/

Also, I would recommend considering the S3 option for storing your shared config. I think it's a mistake to hard code IPs except for `localhost` into cookbooks. Normally we'd use Chef Search to discover the nodes, but that would require every node to reconverge every time you add a new ZK node...which depending on your Chef run interval could mean your cluster acting bizarrely for up to 15 minutes per existing node. So we went the S3 route that Exhibitor supports and its worked quite well.

**Comment by fnicholas** [comment]
I plan to use the chef search method but I'd like to know about the s3  S3 route. what is  S3 route? Also, im not using nodes on AWS.

**Comment by williamsjj** [comment]
@fnicholas None of our nodes are on AWS either. You just configure Exhibitor to store configs on a shared S3 bucket and key. You really need to read the docs on Exhibitor. :) https://github.com/Netflix/exhibitor/wiki/Shared-Configuration

**Comment by aktarali** [comment]
Hi Guys;

I used the following in my wrapper cookbook:
#Wrapper zookeeper cookbook to search through Chef CMDB
include_recipe 'zookeeper'
include_recipe 'zookeeper::service'
i = 0
search(:node,
       "chef_environment:#{node.chef_environment} AND " \
       'roles:zookeeper').map do |n|
  i += 1
  node.set['zookeeper']['config']["server.#{i}"] =
    "#{n['fqdn']}:2888:3888"
end
bash 'add_myid' do
code <<-EOH
  cat `find / \! -type l -name zoo.cfg`|grep `hostname`|cut -d"=" -f1|cut -d"." -f2 > /var/lib/zookeeper/myid
  chown zookeeper:zookeeper /var/lib/zookeeper/myid
  zookeeper-server-initialize --myid=`cat /var/lib/zookeeper/myid` --force
EOH
end

The problem I am having right now on a 3 node zk cluster is that when chef-client runs, each node is getting a different "server.$number" configurations in zoo.cfg. So, each node has different zoo.cfg config.
For example zoo.cfg on node1 looks like:
server.1=ip-192-31-42-197.eu-west-1.compute.internal:2888:3888
server.2=ip-192-31-45-346.eu-west-1.compute.internal:2888:3888
server.3=ip-192-31-41-183.eu-west-1.compute.internal:2888:3888

On node 2:
server.1=ip-192-31-45-346.eu-west-1.compute.internal:2888:3888
server.2=ip-192-31-42-197.eu-west-1.compute.internal:2888:3888
server.3=ip-192-31-41-183.eu-west-1.compute.internal:2888:3888

and so on. I am as you can see using this file to dynamically grab the server.1 string and using it to complete myid param. 

My biggest headache currently is that the configs of zoo.cfg is not consistent across all nodes.

Can anyone assist? On a single node with 1 master, everything works perfectly, however, on a 3 node cluster every time chef-client runs, chef CMDB seems to be giving differing zk values for zoo.cfg. 

Cheers for all your help and time.
Ali.

**Comment by jeffbyrnes** [comment]
@aktarali tweaked the formatting there for ease of readability, but no content changed. I’m on vacation/holiday until next week, but will try to give this some :eyes: then. Stay tuned!

**Comment by aktarali** [comment]
really appreciate the help. The best method is the chef search from cmdb as
it has the information on all nodes and the roles attached. Don't
understand why the configs differ on each chef run.

Thanks
Ali.

**Comment by jeffbyrnes** [comment]
@aktarali so you’re getting the data you need, but Chef Search does not necessarily return things in the same order every time. As such, you’ll want to sort the values before assigning them to the attributes.

**Comment by aktarali** [comment]
Hi,

Sort the values how? Using what order? How to achieve consistency across
all masters?

Hope you're having a great Easter.

Thanks
Ali.

**Comment by jeffbyrnes** [comment]
Alpha order, to start:

```ruby
i = 0
search(
  :node,
  "roles:zookeeper AND chef_environment:#{node.chef_environment}"
).sort.map do |n|
  i += 1
  node.set['zookeeper']['config']["server.#{i}"] = "#{n['fqdn']}:2888:3888"
end
```

As for preserving this order when adding new nodes… that would be much trickier. I’d encourage exploring using Exhibitor w/ its S3 shared config system (the [`exhibitor` cookbook](https://supermarket.chef.io/cookbooks/exhibitor) is a great way to do that) instead of manually managing the config.

**Comment by aktarali** [comment]
Jeff,

Cheers bud. As for s3 config, that's still depending on one additional tool
where node information already exists in chef cmdb. I will treat this and
let you know how I can on.

Thanks for all your help.

Cheers
Ali.
