### ISSUE TITLE
zookeeper 3.4.7 appears to have been pulled

### ISSUE THREAD

**Issue by mihasya** [SimpleFinance/chef-zookeeper#156]
It is gone from all mirrors, having trouble locating any information about why, but I'm probably just not on enough mailing lists :)

This is relevant because it's the default in this cookbook. it causes a checksum mismatch when converging, presumably because it pulls down a 404 page.

**Comment by jeffbyrnes** [comment]
This is growing frustrating. The same thing just happened recently to 3.4.6. Thanks for the heads-up.

**Comment by eherot** [comment]
According to the [interwebs](https://zookeeper.apache.org/) 3.4.6 is now the latest stable release and does indeed appear to be available at the mirror used by this cookbook.

**Comment by eherot** [comment]
Looks like they [pulled it](http://www.mail-archive.com/user@zookeeper.apache.org/msg06572.html) because of a [deadlock issue](https://issues.apache.org/jira/browse/ZOOKEEPER-2347) that caused the server to hang.
