### ISSUE TITLE
cluster config support

### ISSUE THREAD

**Issue by RaidRohana** [SimpleFinance/chef-zookeeper#160]
Can you add cluster mode in the config resource:
```
cluster = {
  clientPort: 2181,
  dataDir: "#{node["zookeper"]["data_dir"]}",
  tickTime: 2000,
  server:server.1=serverip1:2888:3888,
  server:server.2=serverip2:2888:3888,
  server:server.3=serverip3:2888:3888,
  autopurge: {
    snapRetainCount: 1,
    purgeInterval: 1
  }
}
```
Is this supported, if so what is the correct syntax!?
thanks

**Comment by jeffbyrnes** [comment]
@RaidRohana take a look at my comment on #155 about [how to use the attributes to set this up](https://github.com/SimpleFinance/chef-zookeeper/issues/155#issuecomment-168789780).
