### ISSUE TITLE
zookeeper fails to start

### ISSUE THREAD

**Issue by aktarali** [SimpleFinance/chef-zookeeper#171]
Hi Guys;

These params were missing from the attributes file:
  initLimit: 5,
  syncLimit: 2

When I added these, zookeeper started successfully. Is this an oversight?

**Comment by jeffbyrnes** [comment]
@aktarali might be an oversight from the days when this cookbook handled an Exhibitor + ZK installation, and Exhibitor would handle setting those values.

I’ll see about adding those sensible defaults in.
