### ISSUE TITLE
Use our Java

### ISSUE THREAD

**Issue by jakedavis** [SimpleFinance/chef-zookeeper#84]
@miah wrote a kickass [cookbook for Java](https://github.com/SimpleFinance/java) that we should definitely use.

**Comment by jeffbyrnes** [comment]
I'm going to close this, as 76910ae (released in v2.4.2) makes it possible to specify, in a wrapper cookbook, that `node[:zookeeper][:use_java_cookbook] = false` and use your own Java cookbook instead.

I think this is a great pattern to follow for this cookbook, as it’s become a really strong community cookbook for installing Zookeeper, and sticking to using other community cookbooks by default is a Good Thing™.

**Comment by jakedavis** [comment]
Excellent :)
